txt2tsc StageSelect.txt
txt2tsc credit.txt
txt2tsc Head.txt
txt2tsc ArmsItem.txt
txt2tsc Stage\Blcny2.txt
txt2tsc Stage\Comu.txt
txt2tsc Stage\Hell42.txt
txt2tsc Stage\Jenka2.txt
txt2tsc Stage\Little.txt
txt2tsc Stage\MazeB.txt
txt2tsc Stage\Oside.txt
txt2tsc Stage\WeedB.txt
txt2tsc Stage\Barr.txt
txt2tsc Stage\Cave.txt
txt2tsc Stage\Curly.txt
txt2tsc Stage\CurlyS.txt
txt2tsc Stage\Drain.txt
txt2tsc Stage\Plant.txt
txt2tsc Stage\Pool.txt
txt2tsc Stage\EggX.txt
txt2tsc Stage\Hell1.txt
txt2tsc Stage\MazeM.txt
txt2tsc Stage\Pole.txt
txt2tsc Stage\River.txt
txt2tsc Stage\Clock.txt
txt2tsc Stage\Eggs2.txt
txt2tsc Stage\Santa.txt
txt2tsc Stage\Start.txt
txt2tsc Stage\MazeO.txt
txt2tsc Stage\Mimi.txt
txt2tsc Stage\Ballo1.txt
txt2tsc Stage\CentW.txt
txt2tsc Stage\Dark.txt
txt2tsc Stage\Egg6.txt
txt2tsc Stage\EggX2.txt
txt2tsc Stage\SandE.txt
txt2tsc Stage\Cthu.txt
txt2tsc Stage\Jenka1.txt
txt2tsc Stage\Mapi.txt
txt2tsc Stage\Momo.txt
txt2tsc Stage\Ostep.txt
txt2tsc Stage\Pens1.txt
txt2tsc Stage\Prefa2.txt
txt2tsc Stage\Ring1.txt
txt2tsc Stage\Ring3.txt
txt2tsc Stage\Stream.txt
txt2tsc Stage\Almond.txt
txt2tsc Stage\EggR.txt
txt2tsc Stage\Hell2.txt
txt2tsc Stage\Jail2.txt
txt2tsc Stage\MazeI.txt
txt2tsc Stage\MazeS.txt
txt2tsc Stage\Fall.txt
txt2tsc Stage\Itoh.txt
txt2tsc Stage\Jail1.txt
txt2tsc Stage\Lounge.txt
txt2tsc Stage\MazeA.txt
txt2tsc Stage\MazeH.txt
txt2tsc Stage\MazeW.txt
txt2tsc Stage\Sand.txt
txt2tsc Stage\Weed.txt
txt2tsc Stage\WeedD.txt
txt2tsc Stage\Cent.txt
txt2tsc Stage\Chako.txt
txt2tsc Stage\EggR2.txt
txt2tsc Stage\Eggs.txt
txt2tsc Stage\Egg1.txt
txt2tsc Stage\Frog.txt
txt2tsc Stage\Gard.txt
txt2tsc Stage\Malco.txt
txt2tsc Stage\Pens2.txt
txt2tsc Stage\Pixel.txt
txt2tsc Stage\Prefa1.txt
txt2tsc Stage\Priso2.txt
txt2tsc Stage\Shelt.txt
txt2tsc Stage\Statue.txt
txt2tsc Stage\Cemet.txt
txt2tsc Stage\e_Labo.txt
txt2tsc Stage\EgEnd1.txt
txt2tsc Stage\Hell3.txt
txt2tsc Stage\MazeD.txt
txt2tsc Stage\Ring2.txt
txt2tsc Stage\Ballo2.txt
txt2tsc Stage\Blcny1.txt
txt2tsc Stage\e_Blcn.txt
txt2tsc Stage\Kings.txt
txt2tsc Stage\Priso1.txt
txt2tsc Stage\WeedS.txt
txt2tsc Stage\0.txt
txt2tsc Stage\Cthu2.txt
txt2tsc Stage\e_Ceme.txt
txt2tsc Stage\e_Jenk.txt
txt2tsc Stage\e_Malc.txt
txt2tsc Stage\e_Maze.txt
txt2tsc Stage\e_Sky.txt
txt2tsc Stage\EgEnd2.txt
txt2tsc Stage\Hell4.txt
txt2tsc Stage\Island.txt
txt2tsc Stage\MiBox.txt