./Tools/txt2tsc StageSelect.txt
./Tools/txt2tsc credit.txt
./Tools/txt2tsc Head.txt
./Tools/txt2tsc ArmsItem.txt
./Tools/txt2tsc Stage/Blcny2.txt
./Tools/txt2tsc Stage/Comu.txt
./Tools/txt2tsc Stage/Hell42.txt
./Tools/txt2tsc Stage/Jenka2.txt
./Tools/txt2tsc Stage/Little.txt
./Tools/txt2tsc Stage/MazeB.txt
./Tools/txt2tsc Stage/Oside.txt
./Tools/txt2tsc Stage/WeedB.txt
./Tools/txt2tsc Stage/Barr.txt
./Tools/txt2tsc Stage/Cave.txt
./Tools/txt2tsc Stage/Curly.txt
./Tools/txt2tsc Stage/CurlyS.txt
./Tools/txt2tsc Stage/Drain.txt
./Tools/txt2tsc Stage/Plant.txt
./Tools/txt2tsc Stage/Pool.txt
./Tools/txt2tsc Stage/EggX.txt
./Tools/txt2tsc Stage/Hell1.txt
./Tools/txt2tsc Stage/MazeM.txt
./Tools/txt2tsc Stage/Pole.txt
./Tools/txt2tsc Stage/River.txt
./Tools/txt2tsc Stage/Clock.txt
./Tools/txt2tsc Stage/Eggs2.txt
./Tools/txt2tsc Stage/Santa.txt
./Tools/txt2tsc Stage/Start.txt
./Tools/txt2tsc Stage/MazeO.txt
./Tools/txt2tsc Stage/Mimi.txt
./Tools/txt2tsc Stage/Ballo1.txt
./Tools/txt2tsc Stage/CentW.txt
./Tools/txt2tsc Stage/Dark.txt
./Tools/txt2tsc Stage/Egg6.txt
./Tools/txt2tsc Stage/EggX2.txt
./Tools/txt2tsc Stage/SandE.txt
./Tools/txt2tsc Stage/Cthu.txt
./Tools/txt2tsc Stage/Jenka1.txt
./Tools/txt2tsc Stage/Mapi.txt
./Tools/txt2tsc Stage/Momo.txt
./Tools/txt2tsc Stage/Ostep.txt
./Tools/txt2tsc Stage/Pens1.txt
./Tools/txt2tsc Stage/Prefa2.txt
./Tools/txt2tsc Stage/Ring1.txt
./Tools/txt2tsc Stage/Ring3.txt
./Tools/txt2tsc Stage/Stream.txt
./Tools/txt2tsc Stage/Almond.txt
./Tools/txt2tsc Stage/EggR.txt
./Tools/txt2tsc Stage/Hell2.txt
./Tools/txt2tsc Stage/Jail2.txt
./Tools/txt2tsc Stage/MazeI.txt
./Tools/txt2tsc Stage/MazeS.txt
./Tools/txt2tsc Stage/Fall.txt
./Tools/txt2tsc Stage/Itoh.txt
./Tools/txt2tsc Stage/Jail1.txt
./Tools/txt2tsc Stage/Lounge.txt
./Tools/txt2tsc Stage/MazeA.txt
./Tools/txt2tsc Stage/MazeH.txt
./Tools/txt2tsc Stage/MazeW.txt
./Tools/txt2tsc Stage/Sand.txt
./Tools/txt2tsc Stage/Weed.txt
./Tools/txt2tsc Stage/WeedD.txt
./Tools/txt2tsc Stage/Cent.txt
./Tools/txt2tsc Stage/Chako.txt
./Tools/txt2tsc Stage/EggR2.txt
./Tools/txt2tsc Stage/Eggs.txt
./Tools/txt2tsc Stage/Egg1.txt
./Tools/txt2tsc Stage/Frog.txt
./Tools/txt2tsc Stage/Gard.txt
./Tools/txt2tsc Stage/Malco.txt
./Tools/txt2tsc Stage/Pens2.txt
./Tools/txt2tsc Stage/Pixel.txt
./Tools/txt2tsc Stage/Prefa1.txt
./Tools/txt2tsc Stage/Priso2.txt
./Tools/txt2tsc Stage/Shelt.txt
./Tools/txt2tsc Stage/Statue.txt
./Tools/txt2tsc Stage/Cemet.txt
./Tools/txt2tsc Stage/e_Labo.txt
./Tools/txt2tsc Stage/EgEnd1.txt
./Tools/txt2tsc Stage/Hell3.txt
./Tools/txt2tsc Stage/MazeD.txt
./Tools/txt2tsc Stage/Ring2.txt
./Tools/txt2tsc Stage/Ballo2.txt
./Tools/txt2tsc Stage/Blcny1.txt
./Tools/txt2tsc Stage/e_Blcn.txt
./Tools/txt2tsc Stage/Kings.txt
./Tools/txt2tsc Stage/Priso1.txt
./Tools/txt2tsc Stage/WeedS.txt
./Tools/txt2tsc Stage/0.txt
./Tools/txt2tsc Stage/Cthu2.txt
./Tools/txt2tsc Stage/e_Ceme.txt
./Tools/txt2tsc Stage/e_Jenk.txt
./Tools/txt2tsc Stage/e_Malc.txt
./Tools/txt2tsc Stage/e_Maze.txt
./Tools/txt2tsc Stage/e_Sky.txt
./Tools/txt2tsc Stage/EgEnd2.txt
./Tools/txt2tsc Stage/Hell4.txt
./Tools/txt2tsc Stage/Island.txt
./Tools/txt2tsc Stage/MiBox.txt

