tsc2txt StageSelect.tsc
tsc2txt credit.tsc
tsc2txt Head.tsc
tsc2txt ArmsItem.tsc
tsc2txt Stage\Blcny2.tsc
tsc2txt Stage\Comu.tsc
tsc2txt Stage\Hell42.tsc
tsc2txt Stage\Jenka2.tsc
tsc2txt Stage\Little.tsc
tsc2txt Stage\MazeB.tsc
tsc2txt Stage\Oside.tsc
tsc2txt Stage\WeedB.tsc
tsc2txt Stage\Barr.tsc
tsc2txt Stage\Cave.tsc
tsc2txt Stage\Curly.tsc
tsc2txt Stage\CurlyS.tsc
tsc2txt Stage\Drain.tsc
tsc2txt Stage\Plant.tsc
tsc2txt Stage\Pool.tsc
tsc2txt Stage\EggX.tsc
tsc2txt Stage\Hell1.tsc
tsc2txt Stage\MazeM.tsc
tsc2txt Stage\Pole.tsc
tsc2txt Stage\River.tsc
tsc2txt Stage\Clock.tsc
tsc2txt Stage\Eggs2.tsc
tsc2txt Stage\Santa.tsc
tsc2txt Stage\Start.tsc
tsc2txt Stage\MazeO.tsc
tsc2txt Stage\Mimi.tsc
tsc2txt Stage\Ballo1.tsc
tsc2txt Stage\CentW.tsc
tsc2txt Stage\Dark.tsc
tsc2txt Stage\Egg6.tsc
tsc2txt Stage\EggX2.tsc
tsc2txt Stage\SandE.tsc
tsc2txt Stage\Cthu.tsc
tsc2txt Stage\Jenka1.tsc
tsc2txt Stage\Mapi.tsc
tsc2txt Stage\Momo.tsc
tsc2txt Stage\Ostep.tsc
tsc2txt Stage\Pens1.tsc
tsc2txt Stage\Prefa2.tsc
tsc2txt Stage\Ring1.tsc
tsc2txt Stage\Ring3.tsc
tsc2txt Stage\Stream.tsc
tsc2txt Stage\Almond.tsc
tsc2txt Stage\EggR.tsc
tsc2txt Stage\Hell2.tsc
tsc2txt Stage\Jail2.tsc
tsc2txt Stage\MazeI.tsc
tsc2txt Stage\MazeS.tsc
tsc2txt Stage\Fall.tsc
tsc2txt Stage\Itoh.tsc
tsc2txt Stage\Jail1.tsc
tsc2txt Stage\Lounge.tsc
tsc2txt Stage\MazeA.tsc
tsc2txt Stage\MazeH.tsc
tsc2txt Stage\MazeW.tsc
tsc2txt Stage\Sand.tsc
tsc2txt Stage\Weed.tsc
tsc2txt Stage\WeedD.tsc
tsc2txt Stage\Cent.tsc
tsc2txt Stage\Chako.tsc
tsc2txt Stage\EggR2.tsc
tsc2txt Stage\Eggs.tsc
tsc2txt Stage\Egg1.tsc
tsc2txt Stage\Frog.tsc
tsc2txt Stage\Gard.tsc
tsc2txt Stage\Malco.tsc
tsc2txt Stage\Pens2.tsc
tsc2txt Stage\Pixel.tsc
tsc2txt Stage\Prefa1.tsc
tsc2txt Stage\Priso2.tsc
tsc2txt Stage\Shelt.tsc
tsc2txt Stage\Statue.tsc
tsc2txt Stage\Cemet.tsc
tsc2txt Stage\e_Labo.tsc
tsc2txt Stage\EgEnd1.tsc
tsc2txt Stage\Hell3.tsc
tsc2txt Stage\MazeD.tsc
tsc2txt Stage\Ring2.tsc
tsc2txt Stage\Ballo2.tsc
tsc2txt Stage\Blcny1.tsc
tsc2txt Stage\e_Blcn.tsc
tsc2txt Stage\Kings.tsc
tsc2txt Stage\Priso1.tsc
tsc2txt Stage\WeedS.tsc
tsc2txt Stage\0.tsc
tsc2txt Stage\Cthu2.tsc
tsc2txt Stage\e_Ceme.tsc
tsc2txt Stage\e_Jenk.tsc
tsc2txt Stage\e_Malc.tsc
tsc2txt Stage\e_Maze.tsc
tsc2txt Stage\e_Sky.tsc
tsc2txt Stage\EgEnd2.tsc
tsc2txt Stage\Hell4.tsc
tsc2txt Stage\Island.tsc
tsc2txt Stage\MiBox.tsc